### ISSUE TITLE
Rodapé

### ISSUE THREAD

**Issue by erikfig** [brasil-php/blog#1]
No rodapé do blog tem links de Twitter e Github, remover o Twitter e adicionar link para o GitHub e Facebook:

GitHub: https://github.com/brasil-php
Facebook: https://www.facebook.com/phbras/

**Comment by henriqueholanda** [comment]
Hoje o template usado só tem suporte para Github e Twitter.
Tem alguns PRs no repositório pra adicionar mais, só que não foram aceitos ainda.

Podemos fazer um fork dele aqui no brasil-php e implementar isso.
