### ISSUE TITLE
Botão de compartilhamento nos posts do blog

### ISSUE THREAD

**Issue by Jciel** [brasil-php/blog#18]
Talvez seria interessante colocar uns botões de compartilhamento nos posts do blog (face, twitter), para a galera compartilhar, acho que ajudaria também a divulgação do blog.

**Comment by Jciel** [comment]
Acho que da para fechar essa issue, pelo que vi no componente de comentários do Disqus já tem uma opção para compartilhar certo?

**Comment by flavianohonorato** [comment]
Também acho
