### ISSUE TITLE
PHP The Right Way e área de divulgação

### ISSUE THREAD

**Issue by erikfig** [brasil-php/blog#20]
Acho legal ter uma area de destaque no blog com sugestões de projetos legais, até mesmo um banner rotativo com links para blogs/projetos de quem contribuiu, além de dar dicas legais, valoriza quem se contribuiu com o projeto, podemos aceitar:

 - Links úteis ([http://br.phptherightway.com/](http://br.phptherightway.com/), por exemplo)
 - Banners para blogs de quem contribuiu
 - Links para linkedin/curriculo/site pessoal
 - Projetos diversos de contribuintes

Claro que teremos que fazer algo clean e com isso expresso de forma muito transparente, afirmando que aquele "anuncio" é de um contribuinte e que merece ser acessado pelo fato de estar contribuindo para a comunidade, ou algo assim...

O que acham?

**Comment by flavianohonorato** [comment]
Acho uma boa, inclusive hoje adicionei o mesmo esquema adotado no blog do [CakePHPBrasil](http://www.cakephpbrasil.com.br/), onde o autor do post pode incluir sua url, afim de mostrar seu blog, site pessoal, etc.

**Comment by lpj145** [comment]
Apoiado, sem dúvida, isso também incentivará a galera a contribuir, o ruim é que até hoje, to tentando encontrar um programador que não seja muito ocupado :(.

**Comment by rafagouveia** [comment]
Legal a ideia fiz um esquema para o autor de link, e redes sociais, faltou apenas o botão do linkedin mas com certeza ireia adicionar no próximo PR..

`Tela com nome destacado e link`

![Tela com nome destacado e link](https://image.prntscr.com/image/Et8l1rEGSUCMlAS9ehCETQ.png)

`Tela com as redes sociais e descrição para o autor`

![Tela com as redes sociais e descrição para o autor](https://image.prntscr.com/image/4wkGZLprQXq7IdQFi0lMLQ.png)
