### ISSUE TITLE
Comentários do Disqus

### ISSUE THREAD

**Issue by flavianohonorato** [brasil-php/blog#21]
Verificar comentários do Disqus, depois da mudança de layout eles não funcionam mais.

**Comment by henriqueholanda** [comment]
Abri um PR com a correção.

**Comment by flavianohonorato** [comment]
Done, já aceitei lá.

**Comment by erikfig** [comment]
código do disqus ta errado... ta do CakePHP Brasil....

**Comment by Jciel** [comment]
Esta aparecendo links para o blog do CakePHP no componente de comentários. :)

**Comment by flavianohonorato** [comment]
Agora foi, done!
